/**
 * tags/svg.d.mts -- type declarations for tags/svg.mjs (one shorthand
 * function per SVG element, each equivalent to `createSVGElement("tagname",
 * ...)`). Generated to match src/tags/svg.mjs's export list exactly -- keep
 * in sync if that file's exports change.
 */
import type { Child, ElementProps } from "../create-element.mjs";

type TagFn = (props?: ElementProps | Child | null, ...children: Child[]) => Element;

export const a: TagFn;
export const altGlyph: TagFn;
export const altGlyphDef: TagFn;
export const altGlyphItem: TagFn;
export const animate: TagFn;
export const animateColor: TagFn;
export const animateMotion: TagFn;
export const animateTransform: TagFn;
export const animation: TagFn;
export const audio: TagFn;
export const canvas: TagFn;
export const circle: TagFn;
export const clipPath: TagFn;
export const color_profile: TagFn;
export const cursor: TagFn;
export const defs: TagFn;
export const desc: TagFn;
export const discard: TagFn;
export const ellipse: TagFn;
export const feBlend: TagFn;
export const feColorMatrix: TagFn;
export const feComponentTransfer: TagFn;
export const feComposite: TagFn;
export const feConvolveMatrix: TagFn;
export const feDiffuseLighting: TagFn;
export const feDisplacementMap: TagFn;
export const feDistantLight: TagFn;
export const feDropShadow: TagFn;
export const feFlood: TagFn;
export const feFuncA: TagFn;
export const feFuncB: TagFn;
export const feFuncG: TagFn;
export const feFuncR: TagFn;
export const feGaussianBlur: TagFn;
export const feImage: TagFn;
export const feMerge: TagFn;
export const feMergeNode: TagFn;
export const feMorphology: TagFn;
export const feOffset: TagFn;
export const fePointLight: TagFn;
export const feSpecularLighting: TagFn;
export const feSpotLight: TagFn;
export const feTile: TagFn;
export const feTurbulence: TagFn;
export const filter: TagFn;
export const font: TagFn;
export const font_face: TagFn;
export const font_face_format: TagFn;
export const font_face_name: TagFn;
export const font_face_src: TagFn;
export const font_face_uri: TagFn;
export const foreignObject: TagFn;
export const g: TagFn;
export const glyph: TagFn;
export const glyphRef: TagFn;
export const handler: TagFn;
export const hkern: TagFn;
export const iframe: TagFn;
export const image: TagFn;
export const line: TagFn;
export const linearGradient: TagFn;
export const listener: TagFn;
export const marker: TagFn;
export const mask: TagFn;
export const metadata: TagFn;
export const missing_glyph: TagFn;
export const mpath: TagFn;
export const path: TagFn;
export const pattern: TagFn;
export const polygon: TagFn;
export const polyline: TagFn;
export const prefetch: TagFn;
export const radialGradient: TagFn;
export const rect: TagFn;
export const script: TagFn;
export const set: TagFn;
export const solidColor: TagFn;
export const stop: TagFn;
export const style: TagFn;
export const svg: TagFn;
export const Switch: TagFn;
export const symbol: TagFn;
export const tbreak: TagFn;
export const text: TagFn;
export const textArea: TagFn;
export const textPath: TagFn;
export const title: TagFn;
export const tref: TagFn;
export const tspan: TagFn;
export const unknown: TagFn;
export const use: TagFn;
export const video: TagFn;
export const view: TagFn;
export const vkern: TagFn;
